### ISSUE TITLE
Cannot Download the weights 

### ISSUE THREAD

**Issue by Anang1502** [sun-asterisk-research/stamp_processing#6]
I ran the code as given in example.md but the code fails in downloading the weights. I tried to manually download the weights from the link given in the error but even that link is not accessible. Below is the code i ran.

### **CODE** 
import numpy as np
import matplotlib.pyplot as plt
import pdf2image
import cv2
from stamp_processing.detector import StampDetector

def imshow(img, figsize=(10, 10)):
    fig, ax = plt.subplots(1, 1, figsize=figsize)
    ax.axis('off')
    ax.imshow(img)

detector = StampDetector(model_path=None)

images = pdf2image.convert_from_path('sample.pdf')
image = np.array(images[0])
preds = detector.detect([image])
for box in preds[0]:
    cv2.rectangle(image, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 255)
imshow(image)

### **ERROR**

INFO - Downloading stamp detection weight from google drive'
Cached Downloading: tmp\stamp_detector.pt
ERROR - ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))'
ERROR - Something went wrong when downloading the weight'
ERROR - Check your internet connection or manually download the weight at https://drive.google.com/file/d/1YHH7pLoZEdyxw2AoLz9G4lrq6uuxweYB/view?usp=sharing'
INFO - Finished downloading. Weight is saved at tmp\stamp_detector.pt'
ERROR - Cache may be out of date, try `force_reload=True`. See https://github.com/ultralytics/yolov5/issues/36 for help.'
ERROR - There is something wrong when loading detector weight'
ERROR - Please make sure you provide the correct path to the weight or mannually download the weight at https://drive.google.com/file/d/1YHH7pLoZEdyxw2AoLz9G4lrq6uuxweYB/view?usp=sharing'
Traceback (most recent call last):
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\module\yolov5\hubconf.py", line 31, in _create
    model = attempt_load(path, map_location=device)  # download/load FP32 model
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\module\yolov5\models\experimental.py", line 120, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\stamp_detector.pt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\detector.py", line 41, in __init__
    self.model, self.stride = load_yolo_model(model_path, device=device)
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\utils.py", line 31, in load_yolo_model
    model = torch.hub.load(str(YOLO_DIR), "custom", path=weight_path, source="local", force_reload=True)
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\torch\hub.py", line 339, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\torch\hub.py", line 368, in _load_local
    model = entry(*args, **kwargs)
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\module\yolov5\hubconf.py", line 47, in custom
    return _create(path, autoshape=autoshape, verbose=verbose, device=device)
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\module\yolov5\hubconf.py", line 42, in _create
    raise Exception(s) from e
Exception: Cache may be out of date, try `force_reload=True`. See https://github.com/ultralytics/yolov5/issues/36 for help.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\My Projects\stamp_detection\stamp_detect_venv\lib\site-packages\stamp_processing\detector.py", line 50, in __init__
    raise FileNotFoundError()
FileNotFoundError
Backend TkAgg is interactive backend. Turning interactive mode on.

Process finished with exit code 1

**Comment by Anang1502** [comment]
I think the issue was with the website server. I tried to run the code sometime later and it was working fine for me.
